// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhIikTqgJoSWSzwkb1Adr15mDS9iqaXD0',
    appId: '1:13121685108:web:a7f284b26eada47098b321',
    messagingSenderId: '13121685108',
    projectId: 'climate-c11a3',
    authDomain: 'climate-c11a3.firebaseapp.com',
    storageBucket: 'climate-c11a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8dIUKFRYFLOA_hAfqhsHhytK287tr58g',
    appId: '1:13121685108:android:410400be5346e70798b321',
    messagingSenderId: '13121685108',
    projectId: 'climate-c11a3',
    storageBucket: 'climate-c11a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqxZF4YfxoOybj-ERnHVnKZ8MfDjWw3ac',
    appId: '1:13121685108:ios:517e9086d1b1833298b321',
    messagingSenderId: '13121685108',
    projectId: 'climate-c11a3',
    storageBucket: 'climate-c11a3.appspot.com',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqxZF4YfxoOybj-ERnHVnKZ8MfDjWw3ac',
    appId: '1:13121685108:ios:ef3bc9ee13d90fdc98b321',
    messagingSenderId: '13121685108',
    projectId: 'climate-c11a3',
    storageBucket: 'climate-c11a3.appspot.com',
    iosBundleId: 'com.example.firstApp.RunnerTests',
  );
}
