# Generated by Django 4.2.5 on 2023-10-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherpref',
            name='lastNotified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weatherpref',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
