# Generated by Django 4.2.5 on 2023-10-10 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherpref_lastnotified_weatherpref_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherpref',
            name='lastNotified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
